include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    prefer_const_constructors: true
    prefer_single_quotes: true
